#!/bin/sh
#
# Provision everything, Puppet? Boxen? Custom?

# Oh-My-ZSH!
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
rm -rf ~/.oh-my-zsh/custom
ln -s ~/.dotfiles/oh-my-zsh-custom ~/.oh-my-zsh/custom

rm -rf ~/.vim
ln -s ~/.dotfiles/.vim ~/.vim
# Install configured Bundles
# vim +BundleInstall +qall

# TODO