#!/bin/sh
#husky 0.13.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd .

has_hook_script postcommit || exit 0

export PATH=$PATH:/usr/local/bin:/usr/local

command_exists npm || {
  echo >&2 "> husky - Can't find npm in PATH. Skipping postcommit script in package.json"
  exit 0
}

echo
echo "> postcommit hook - npm run -s postcommit"
echo

export GIT_PARAMS="$*"
npm run -s postcommit || {
  echo
  echo "> postcommit - post-commit hook failed (add --no-verify to bypass)"
  echo "> postcommit - to debug, use 'npm run postcommit'"
  exit 1
}
