#!/bin/sh

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
  if [ "$local_sha" = $z40 ]
  then
    # Handle delete
    :
  else
    if [ "$remote_sha" = $z40 ]
    then
      # New branch, examine all commits since master
      range="$(git merge-base $local_sha master)..$local_sha"
    else
      # Update to existing branch, examine new commits
      range="$remote_sha..$local_sha"
    fi

    # Check for WIP commits
    commit=`git rev-list -n 1 --grep '^WIP' -i "$range"`
    if [ -n "$commit" ]
    then
      echo "\nPush rejected: WIP commit detected: $commit\n"
      exit 1
    fi

    # Check for autosquash commits
    commit=`git rev-list -n 1 --grep '^\(fixup\|squash\)!' "$range"`
    if [ -n "$commit" ]
    then
      echo "\nPush rejected: autosquash commit detected\n"
      exit 1
    fi
  fi
done

#husky 0.13.3

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

load_nvm () {
  export $1=$2
  [ -s "$2/nvm.sh" ] && . $2/nvm.sh
  command_exists nvm && [ -f .nvmrc ] && nvm use
}

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd .

has_hook_script prepush || exit 0

export PATH=$PATH:/usr/local/bin:/usr/local
load_nvm BREW_NVM_DIR /usr/local/opt/nvm

load_nvm NVM_DIR /Users/nrako/.nvm

command_exists npm || {
  echo >&2 "> husky - Can't find npm in PATH. Skipping prepush script in package.json"
  exit 0
}

echo
echo "> husky - npm run -s prepush"
echo

export GIT_PARAMS="$*"
npm run -s prepush || {
  echo
  echo "> husky - pre-push hook failed (add --no-verify to bypass)"
  echo "> husky - to debug, use 'npm run prepush'"
  exit 1
}
